---
deployment:
 tasks:
 - export DEPLOYPATH=/home/user/public_html/
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp battery.html $DEPLOYPATH
 - /bin/cp contact.html $DEPLOYPATH
 - /bin/cp export.html $DEPLOYPATH
 - /bin/cp tyre.html $DEPLOYPATH
 - /bin/cp -R img $DEPLOYPATH
 - /bin/cp -R js $DEPLOYPATH
 - /bin/cp -R scss $DEPLOYPATH
 - /bin/cp -R css $DEPLOYPATH